### ISSUE TITLE
Program freeze/crash on startup

### ISSUE THREAD

**Issue by cbrt-x** [Jadefalke2/TAS-editor#20]
Sometimes the program freezes or crashes immeadiatly on start up. I have no idea why this happens and it only seems to happen in the .jar and *not* in the dev version in an IDE

**Comment by MonsterDruide1** [comment]
![TAS-Editor-freeze](https://user-images.githubusercontent.com/26349348/117818742-3080f500-b269-11eb-8827-f7c7fe29bae1.png)
It does also happen with the dev version sometimes, but randomly and unpredictable...

**Comment by MonsterDruide1** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "alignment" because "total" is null
	at java.desktop/javax.swing.SizeRequirements.calculateAlignedPositions(SizeRequirements.java:463)
	at java.desktop/javax.swing.BoxLayout.layoutContainer(BoxLayout.java:427)
	at java.desktop/java.awt.Container.layout(Container.java:1538)
	at java.desktop/java.awt.Container.doLayout(Container.java:1527)
	at java.desktop/java.awt.Container.validateTree(Container.java:1723)
	at java.desktop/java.awt.Container.validateTree(Container.java:1732)
	at java.desktop/java.awt.Container.validateTree(Container.java:1732)
	at java.desktop/java.awt.Container.validateTree(Container.java:1732)
	at java.desktop/java.awt.Container.validateTree(Container.java:1732)
	at java.desktop/java.awt.Container.validateTree(Container.java:1732)
	at java.desktop/java.awt.Container.validateTree(Container.java:1732)
	at java.desktop/java.awt.Container.validateTree(Container.java:1732)
	at java.desktop/java.awt.Container.validate(Container.java:1658)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:745)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:742)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1883)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

This is the stacktrace. It doesn't seem related to any TAS-Editor-caused stuff, so my best guess is that the Themes break something internally.

**Comment by MonsterDruide1** [comment]
Found the issue: The custom PopupMenu of PianoRoll caused the L&F update to go crazy. It seems fixed with the latest commit, so I'm just going to close this for now... if it starts crashing again due to layout issues, please re-open this issue or create a new one.
